framework:
    # ...
     http_client:
        scoped_clients:
            api.client:
                base_uri: '%env(resolve:APP_URL_API)%'
                headers:
                    Accept: 'application/json'
                    Content-Type: 'application/json'